import BookModel from '../models/book'
import CategoryModel from '../models/category'
import IBook from '../interfaces/models/book'
import { slugifyString } from '../helpers/common'

const books: IBook[] = [
  {
    'isbn': '9780143128540',
    'title': 'Rich Dad Poor Dad',
    'summary': 'A personal finance classic exploring the mindset differences between the rich and the poor.',
    'author': 'Robert T. Kiyosaki',
    'description': 'Teaches how to achieve financial independence through investing, real estate, and entrepreneurship.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780143128540-L.jpg',
    'category_id': '68985147b5680055837541c9',
    'slug': 'rich-dad-poor-dad',
    'language': 'English',
    'published_at': new Date('1997-04-01'),
  },
  {
    'isbn': '9780066620992',
    'title': 'Good to Great',
    'summary': 'Examines why some companies make the leap to greatness and others don\'t.',
    'author': 'Jim Collins',
    'description': 'A study of 28 companies over five years to understand what separates good companies from great ones.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'good-to-great',
    'language': 'English',
    'published_at': new Date('2001-10-16'),
  },
  {
    'isbn': '9780307465351',
    'title': 'The Lean Startup',
    'summary': 'How today\'s entrepreneurs use continuous innovation to create successful businesses.',
    'author': 'Eric Ries',
    'description': 'Introduces the lean startup methodology for developing products faster and more efficiently.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'the-lean-startup',
    'language': 'English',
    'published_at': new Date('2011-09-13'),
  },
  {
    'isbn': '9780385349949',
    'title': 'The Innovators',
    'summary': 'A history of the digital revolution and the pioneers who made it possible.',
    'author': 'Walter Isaacson',
    'description': 'Chronicles the stories of inventors, hackers, and entrepreneurs who created the computer and the internet.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780385349949-L.jpg',
    'category_id': '68985147b5680055837541cb',
    'slug': 'the-innovators',
    'language': 'English',
    'published_at': new Date('2014-10-07'),
  },
  {
    'isbn': '9781982134488',
    'title': 'The Ride of a Lifetime',
    'summary': 'Lessons learned from 15 years as CEO of the Walt Disney Company.',
    'author': 'Robert Iger',
    'description': 'Reveals leadership lessons and business strategies from one of the most successful CEOs in the entertainment industry.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9781982134488-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'the-ride-of-a-lifetime',
    'language': 'English',
    'published_at': new Date('2019-09-23'),
  },
  {
    'isbn': '9780062316110',
    'title': 'The One Thing',
    'summary': 'The surprisingly simple truth behind extraordinary results.',
    'author': 'Gary Keller',
    'description': 'Focuses on narrowing your concentration to achieve greater success in work and life.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780062316110-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'the-one-thing',
    'language': 'English',
    'published_at': new Date('2013-04-01'),
  },
  {
    'isbn': '9780307588371',
    'title': 'Rework',
    'summary': 'A different approach to running a business successfully.',
    'author': 'Jason Fried & David Heinemeier Hansson',
    'description': 'Challenges traditional business practices and encourages a more practical, efficient way of working.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'rework',
    'language': 'English',
    'published_at': new Date('2010-03-09'),
  },
  {
    'isbn': '9780062457714',
    'title': 'Measure What Matters',
    'summary': 'How Google, Bono, and the Gates Foundation rock the world with OKRs.',
    'author': 'John Doerr',
    'description': 'Explains the objectives and key results (OKRs) system that drives success at companies like Google.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'measure-what-matters',
    'language': 'English',
    'published_at': new Date('2018-04-24'),
  },
  {
    'isbn': '9781524763169',
    'title': 'Atomic Habits',
    'summary': 'Tiny changes that lead to remarkable results.',
    'author': 'James Clear',
    'description': 'Breaks down the science of habits and provides a system for continuous improvement.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9781524763169-L.jpg',
    'category_id': '68985147b5680055837541c9',
    'slug': 'atomic-habits',
    'language': 'English',
    'published_at': new Date('2018-10-16'),
  },
  {
    'isbn': '9780141033570',
    'title': 'Outliers',
    'summary': 'The story of success and what makes high-achievers different.',
    'author': 'Malcolm Gladwell',
    'description': 'Explores factors that contribute to success beyond talent and hard work.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780141033570-L.jpg',
    'category_id': '68985147b5680055837541ca',
    'slug': 'outliers',
    'language': 'English',
    'published_at': new Date('2008-11-18'),
  },
  {
    'isbn': '9781591846352',
    'title': 'The Power of Habit',
    'summary': 'Why we do what we do in life and business.',
    'author': 'Charles Duhigg',
    'description': 'Explains the science of habit formation and how to change bad habits into good ones.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9781591846352-L.jpg',
    'category_id': '68985147b5680055837541c9',
    'slug': 'the-power-of-habit',
    'language': 'English',
    'published_at': new Date('2012-02-28'),
  },
  {
    'isbn': '9780132350884',
    'title': 'Clean Code',
    'summary': 'A handbook of agile software craftsmanship.',
    'author': 'Robert C. Martin',
    'description': 'Provides guidelines, best practices, and principles for writing clean, maintainable code.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg',
    'category_id': '68985147b5680055837541cb',
    'slug': 'clean-code',
    'language': 'English',
    'published_at': new Date('2008-08-01'),
  },
  {
    'isbn': '9780201616224',
    'title': 'The Pragmatic Programmer',
    'summary': 'Your journey to mastery.',
    'author': 'Andrew Hunt & David Thomas',
    'description': 'Covers practical tips and philosophies for becoming a better programmer.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg',
    'category_id': '68985147b5680055837541cb',
    'slug': 'the-pragmatic-programmer',
    'language': 'English',
    'published_at': new Date('1999-10-20'),
  },
  {
    'isbn': '9780393356182',
    'title': 'Deep Work',
    'summary': 'Rules for focused success in a distracted world.',
    'author': 'Cal Newport',
    'description': 'Teaches strategies for deep focus and productivity in a world full of distractions.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9780393356182-L.jpg',
    'category_id': '68985147b5680055837541c9',
    'slug': 'deep-work',
    'language': 'English',
    'published_at': new Date('2016-01-05'),
  },
  {
    'isbn': '9781781254073',
    'title': 'The Art of Thinking Clearly',
    'summary': 'Better thinking through 99 cognitive biases explained.',
    'author': 'Rolf Dobelli',
    'description': 'Explains common thinking errors and how to avoid them in decision-making.',
    'cover_url': 'https://covers.openlibrary.org/b/isbn/9781781254073-L.jpg',
    'category_id': '68985147b5680055837541c9',
    'slug': 'the-art-of-thinking-clearly',
    'language': 'English',
    'published_at': new Date('2013-04-02'),
  },
]


export default async function seedBooks() {
  const fictionCategory = await CategoryModel.findOne({ name: 'technology' })

  await BookModel.findOneAndUpdate(
    { isbn: '9780000000001' },
    {
      $setOnInsert: {
        isbn: '9780000000001',
        title: 'Sample Book',
        author: 'Book Club',
        summary: 'A sample seeded book.',
        description: 'This is a placeholder seeded book for development.',
        slug: 'sample-book',
        category_id: fictionCategory?._id,
        language: 'English',
      },
    },
    { upsert: true, new: true },
  )

  const upsertBooksPromises = books.map(async (book: IBook) => {
    return BookModel.findOneAndUpdate({
      isbn: book.isbn,
    }, {
      $setOnInsert: {
        ...book,
        slug: slugifyString(`${book.title} ${book.author}`),
      },
    }, {
      upsert: true,
      new: true,
    })
  })
  await Promise.all(upsertBooksPromises)  
} 