# [Builder Stage]
FROM node:22.10.0-alpine AS builder

WORKDIR /app

# Layer cache
COPY packages/web/package*.json ./packages/web/
COPY packages/web/yarn.lock ./packages/web/

# Install dependencies
RUN cd packages/web && \
    yarn install --production --frozen-lockfile && \
    yarn cache clean

# Copy the web code
COPY packages/web ./packages/web

# Build frontend with environment variables
ARG REACT_APP_API_URL

# Set environment variables during build
ENV REACT_APP_API_URL=$REACT_APP_API_URL

# Build frontend
RUN cd packages/web && yarn build

# [Production Stage]
FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy build files from builder stage
COPY --from=builder /app/packages/web/build .

EXPOSE 80
# Start serve
CMD ["nginx", "-g", "daemon off;"]